const data = [
    {
      id: 17200576,
      title: "Journey to Hogwarts",
      author: "J.K. Rowling",
      category: "Fantasy",
      price: 19.99,
      pageCount: 320,
      image: "https://covers.openlibrary.org/b/id/2520429-M.jpg",
    },
    {
      id: 15954006,
      title: "Inside Hogwarts",
      author: "J.K. Rowling",
      category: "Activity",
      price: 42.99,
      pageCount: 150,
      image: "https://covers.openlibrary.org/b/id/2520430-M.jpg",
    },
    {
      id: 16384516,
      title: "Harry Potter and the Goblet of Fire",
      author: "J.K. Rowling",
      category: "Fantasy",
      price: 25.99,
      pageCount: 636,
      image: "https://covers.openlibrary.org/b/id/12775900-M.jpg",
    },
    {
      id: 14296534,
      title: "Harry Potter and the Order of the Phoenix",
      author: "J.K. Rowling",
      category: "Fantasy",
      price: 23.49,
      pageCount: 870,
      image: "https://covers.openlibrary.org/b/id/11416565-M.jpg",
    },
    {
      id: 14530450,
      title: "The Great Gatsby (Silver Screen Edition)",
      author: "F. Scott Fitzgerald",
      category: "Classic",
      price: 75.99,
      pageCount: 180,
      image: "https://covers.openlibrary.org/b/id/12791857-M.jpg",
    },
    {
      id: 18810398,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      category: "Fantasy",
      price: 20.49,
      pageCount: 310,
      image: "https://covers.openlibrary.org/b/id/394001-M.jpg",
    },
    {
      id: 13597674,
      title: "The Name of the Wind",
      author: "Patrick Rothfuss",
      category: "Fantasy",
      price: 17.99,
      pageCount: 662,
      image: "https://covers.openlibrary.org/b/id/6282709-M.jpg",
    },
    {
      id: 20778556,
      title: "The Two Towers: The Lord of the Rings",
      author: "J.R.R. Tolkien",
      category: "Fantasy",
      price: 18.49,
      pageCount: 352,
      image: "https://covers.openlibrary.org/b/id/13220226-M.jpg",
    },
    {
      id: 20101114,
      title: "Frankenstein (Silver Screen Edition)",
      author: "Mary Shelley",
      category: "Horror",
      price: 14.99,
      pageCount: 280,
      image: "https://covers.openlibrary.org/b/id/12791860-M.jpg",
    },
    {
      id: 17798828,
      title: "Bogar bárd meséi",
      author: "J.K. Rowling",
      category: "Fantasy",
      price: 11.99,
      pageCount: 128,
      image: "https://covers.openlibrary.org/b/id/9326689-M.jpg",
    },
    {
        id: 13597674,
        title: "The Name of the Wind",
        author: "Patrick Rothfuss",
        category: "Fantasy",
        price: 30.99,
        pageCount: 662,
        image: "https://covers.openlibrary.org/b/id/6282709-M.jpg",
      },
      {
        id: 20778556,
        title: "The Two Towers: The Lord of the Rings",
        author: "J.R.R. Tolkien",
        category: "Fantasy",
        price: 18.49,
        pageCount: 352,
        image: "https://covers.openlibrary.org/b/id/13220226-M.jpg",
      },
      {
        id: 20101114,
        title: "Frankenstein (Silver Screen Edition)",
        author: "Mary Shelley",
        category: "Horror",
        price: 14.99,
        pageCount: 280,
        image: "https://covers.openlibrary.org/b/id/12791860-M.jpg",
      },
      {
        id: 17798828,
        title: "Bogar bárd meséi",
        author: "J.K. Rowling",
        category: "Fantasy",
        price: 30.99,
        pageCount: 128,
        image: "https://covers.openlibrary.org/b/id/9326689-M.jpg",
      },
  ];
   export default data;